<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.1.80</Version>
    <PackageProjectUrl>https://github.com/miqote69/CrescentAtlas</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IconUrl>https://raw.githubusercontent.com/miqote69/CrescentAtlas/main/images/icon-v44.png</IconUrl>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
    <Content Include="Assets\Audio\CrescentAtlas.PotAlert.ja.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>CrescentAtlas.PotAlert.ja.wav</TargetPath>
    </Content>
    <Content Include="Assets\Audio\CrescentAtlas.PotAppeared.ja.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>CrescentAtlas.PotAppeared.ja.wav</TargetPath>
    </Content>
    <Content Include="Assets\Audio\CrescentAtlas.PotOneMinute.ja.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>CrescentAtlas.PotOneMinute.ja.wav</TargetPath>
    </Content>
    <Content Include="Assets\Audio\CrescentAtlas.PotAlert.en.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>CrescentAtlas.PotAlert.en.wav</TargetPath>
    </Content>
    <Content Include="Assets\Audio\CrescentAtlas.PotAppeared.en.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>CrescentAtlas.PotAppeared.en.wav</TargetPath>
    </Content>
    <Content Include="Assets\Audio\CrescentAtlas.PotOneMinute.en.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>CrescentAtlas.PotOneMinute.en.wav</TargetPath>
    </Content>
  </ItemGroup>
</Project>
