using CrescentAtlas.Contracts;
using CrescentAtlas.Data;
using Dalamud.Plugin.Services;
using FFXIVClientStructs.FFXIV.Client.Game.InstanceContent;
using FFXIVClientStructs.FFXIV.Client.Game.UI;
using FFXIVClientStructs.STD;
using Lumina.Excel.Sheets;

namespace CrescentAtlas.Runtime;

/// <summary>
/// Reads the marker list generated by the active Occult Crescent director.
/// This can expose the selected Magical Elixir destination before its EventObj
/// is close enough to enter Dalamud's ObjectTable.
/// </summary>
public sealed class OccultCrescentMapMarkerTargetSource(
    IDataManager dataManager,
    IPluginLog log)
{
    private readonly HashSet<string> recordedKeys = new(StringComparer.Ordinal);

    public unsafe IReadOnlyList<AtlasMarker> Scan(
        string sessionId,
        uint territoryId,
        string territoryName,
        uint currentMapId,
        OccultCrescentMapLayer mapLayer,
        DateTimeOffset observedAtUtc,
        out IReadOnlyList<ObservationRecord> observations)
    {
        var result = new List<AtlasMarker>();
        var newObservations = new List<ObservationRecord>();
        observations = newObservations;

        if (territoryId > ushort.MaxValue
            || mapLayer != OccultCrescentMapLayer.Surface)
        {
            return result;
        }

        StdVector<MapMarkerData> nativeMarkers = default;
        try
        {
            var director = PublicContentOccultCrescent.GetInstance();
            if (director == null)
                return result;

            director->PopulateMapMarkers((ushort)territoryId, &nativeMarkers);
            var levelSheet = dataManager.GetExcelSheet<Level>();

            for (var index = 0; index < nativeMarkers.Count; index++)
            {
                ref readonly var native = ref nativeMarkers[index];
                if (native.TerritoryTypeId != 0
                    && native.TerritoryTypeId != territoryId)
                {
                    continue;
                }

                if (native.MapId != 0
                    && currentMapId != 0
                    && native.MapId != currentMapId)
                {
                    continue;
                }

                var tooltip = native.TooltipString == null
                    ? string.Empty
                    : native.TooltipString->ToString();
                var levelObjectId = 0u;
                if (native.LevelId != 0
                    && levelSheet.TryGetRow(native.LevelId, out var level))
                {
                    levelObjectId = level.Object.RowId;
                }

                var dataId = MagicalElixirMapMarkerClassifier.ResolveTargetDataId(
                    native.ObjectiveId,
                    levelObjectId,
                    tooltip);
                if (dataId == 0
                    || !IsFinite(native.Position))
                {
                    continue;
                }

                var label = MagicalElixirMapMarkerClassifier.ResolveLabel(dataId, tooltip);
                var key = FormattableString.Invariant(
                    $"native-map-pot-target:{territoryId}:{dataId}:{native.LevelId}:{native.Position.X:F2}:{native.Position.Y:F2}:{native.Position.Z:F2}");
                var marker = new AtlasMarker(
                    key,
                    AtlasMarkerKind.PotTarget,
                    label,
                    native.Position,
                    observedAtUtc,
                    IsActive: true,
                    territoryId,
                    dataId,
                    native.DataId,
                    TreasureType: MagicalElixirMapMarkerClassifier.ResolveTreasureType(dataId),
                    IconId: native.IconId);
                result.Add(marker);

                if (!recordedKeys.Add(key))
                    continue;

                newObservations.Add(new ObservationRecord
                {
                    SessionId = sessionId,
                    ObservedAtUtc = observedAtUtc,
                    Source = ObservationSource.NativeMap,
                    Kind = "pot-target",
                    Key = key,
                    TerritoryId = territoryId,
                    TerritoryName = territoryName,
                    DataId = dataId,
                    EventId = native.DataId,
                    Name = label,
                    X = native.Position.X,
                    Y = native.Position.Y,
                    Z = native.Position.Z,
                    IsActive = true,
                    Properties = new Dictionary<string, string>
                    {
                        ["targetType"] = "magic-pot-destination",
                        ["markerSource"] = "occult-crescent-director",
                        ["levelId"] = native.LevelId.ToString(),
                        ["objectiveId"] = native.ObjectiveId.ToString(),
                        ["mapId"] = native.MapId.ToString(),
                        ["iconId"] = native.IconId.ToString(),
                        ["markerType"] = native.MarkerType.ToString(),
                    },
                });
            }
        }
        catch (Exception ex)
        {
            log.Debug(ex, "Failed to read Occult Crescent native map markers.");
        }
        finally
        {
            nativeMarkers.Dispose();
        }

        return result
            .GroupBy(marker => marker.Key, StringComparer.Ordinal)
            .Select(group => group.First())
            .ToArray();
    }

    private static bool IsFinite(Vector3 position)
        => float.IsFinite(position.X)
           && float.IsFinite(position.Y)
           && float.IsFinite(position.Z);
}
